config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  resources :cocktails do
    resources :doses, only: [:new, :create, :destroy]
  end

end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  has_many :doses, dependent: :destroy
  has_many :ingredients, :through => :doses 
  validates :name, uniqueness: true, presence: :true
end

app/models/dose.rb
class Dose < ActiveRecord::Base
  belongs_to :cocktail
  belongs_to :ingredient

  validates_uniqueness_of :cocktail_id, :scope => [:ingredient_id]
  validates :description, presence: :true
  validates :ingredient, presence: :true
  validates :cocktail, presence: :true
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :doses
  validates :name, presence: :true, uniqueness: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else 
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :find_cocktail, only: [:new, :create, :index, :destroy]

  def index
    @doses = Doses.all
  end

  def new
    @dose = Dose.new
    @available_ingredients = Ingredient.all - @cocktail.ingredients
  end

  def create
    @dose = @cocktail.doses.build(dose_params)
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else 
      render "new"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktails_path
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

  def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: url('http://www.patricknagtegaal.nl/wordpress/wp-content/uploads/2012/11/cocktails-4.jpg');">
  <div class='container text-center padded'>    
    <div class="banner-content">
      <h1>Cocktails Index</h1>
      <div class="text-center">
        <button type="button" class="btn btn-default"><%= link_to 'Create a cocktail', new_cocktail_path %></button>
      </div>
    </div>
  </div>
</div>

</div> 
</div>
</div>
<div class= 'container padded'>
  <div class="row">
    <% @cocktails.each do |cocktail| %>
    <div class="col-xs-12 col-sm-6 col-xs-4">
      <div class="card" style="background-image: url(http://www.letsgobrazil.nl/wp-content/uploads/2012/09/Caipirinha.jpg);">
        <div class="card-category">
          <%= cocktail.id %>
          <%= link_to cocktail.name, cocktail_path(cocktail) %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="text-center padded">
<h1> Welcome to the Cocktail Creator </h1>
<br>
  <%= form_for(@cocktail) do |f| %>
  <br>
  <%= f.text_field :name %>
  <br>
  <%= f.label :name %>
  <br>
  <%= f.submit %>
  <% end %>
  <br>
</div>
<div class='padded'>
</div>
<div class="text-center padded">
  <button type="button" class="btn btn-default"><%= link_to 'Back to Index', cocktails_path %></button>
</div>

app/views/cocktails/show.html.erb
<div class='container text-center'>
  <h1>You selected: <%= @cocktail.name %></h1>

</div>
<br>
<div class="text-center padded">
  <ul class ="list-unstyled">
    <% @cocktail.doses.each do |dose| %>
    <li>Dosage: <%= dose.description %> <br> Ingredient :<%= Ingredient.find(dose.ingredient_id).name %> <br>
      <button type="button" class="btn btn-default"><%= link_to 'Delete this Ingredient', cocktail_doses_path(@cocktail), method: :delete, :data => { :confirm => "Are your sure?"} %></button></li>
      <br>
      <% end %>
    </ul>
    <br>
    <button type="button"><%= link_to "Add a new ingredient to this cocktail", new_cocktail_dose_path(@cocktail) %></button>
  </div>

  <div class="text-center padded">

  </div>


  <div class='padded'>
  </div>


  <div class="text-center padded">
    <button type="button" class="btn btn-default"><%= link_to 'Back to Index', cocktails_path %></button>
  </div>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
<div class='text-center'>
  <h1>Doses</h1>
  <h1> Add a new Ingredient to <%= @cocktail.name %></h1>
</div>


<%= simple_form_for [:cocktail, @dose] do |f| %>
<%= f.error_notification %>

<%= f.input :description %>
<%= f.input :ingredient_id, collection: @available_ingredients%>
<%= f.submit  %>
<% end %>
<div class="text-center">
  <button type="button" class="btn btn-default"><%= link_to 'Back to Cocktail', cocktail_path(@cocktail) %></button>
</div>
<br>
<div class="text-center">
  <button type="button" class="btn btn-default"><%= link_to 'Back to Index', cocktails_path %></button>
</div>

app/views/doses/show.html.erb
<h1>Doses#show</h1>
<p>Find me in app/views/doses/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CocktailApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "shared/navbar" %>
<%= yield %>
<%= render "shared/footer" %>

</body>
</html>

app/views/shared/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <!-- <div class="col-sm-6">CC0 2016 DanielGordon. No Right Reserved</div> -->
      <div class="col-sm-6 text-right">
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation" id="nav">
  <div class="container">
   <div class="navbar-header">
     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
      <span class="sr-only">Toggle navigation</span>
      <i class="fa fa-reorder"></i>
    </button>
          <!-- <a class="navbar-brand" href="#">
            <img src="assets/img/logo/logo.png" alt="Logo">
          </a> -->
        </div>
        <div class="collapse navbar-collapse navbar-right" id="navbar">
         <ul class="nav navbar-nav">
     <!--      <li><a href="#home">Home <span class="sr-only">home</span></a></li>
          <li><a href="#me">Me</a></li>
          <li><a href="#work_experience">Work Experience</a></li>
          <li><a href="#education">Education</a></li>
          <li><a href="#travels">Travels</a></li>
          <li><a href="#skills">Skills</a></li>
          <li><a href="#contact">Contact</a></li> -->
        </ul>
      </div>
    </div>
  </nav>